export const KOLLECTIVE_SUPABASE_URL = process.env.NEXT_PUBLIC_KOLLECTIVE_SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://dzlmtvodpyhetvektfuo.supabase.co';
export const KOLLECTIVE_SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_KOLLECTIVE_SUPABASE_PUBLISHABLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || '';
