"use client";
import {useEffect,useMemo,useState} from "react";
type Task={id:string;title:string;brand:string;category:string;target:number;done:number;status:"active"|"background"|"complete";owner:string;proof:string;time:string};
const brands=["DORSEY","HAKUNA MATATA","KOLLECTIVE / OG","BRAVO NYE — SOUTHLAKE","GOOD TIMES","S.O.S.","BODEGA / MISTER MANUFACTURING","STUSH","FĚNYX","MAKE ATL GREAT AGAIN","INNER CIRCLE","MEMORY MACHINE","BEVCO + BEVERAGES","CASPER GROUP","SOLE EXCHANGE"];
const background=["LUXE ON DEMAND","ON CALL ALL DAY","MISSION 365","NATIONAL TRACK & FIELD LEAGUE","BRIO (ATL)","EXCLAMATION POINT","WINTER WHITE","NYE","FIND NEW RESTAURANT — ATLANTA"];
const categories=["Revenue / Closing","Calls / Follow-ups","Email Marketing","Email Outreach","Social Posts","Stories","Social Engagement","Creative / Graphics","Research / Updates","Enrichment / Scraping","Lead Sourcing","Targets Loaded","Ambassadors","Onboarding","Grants / Sponsors","App / Website QA","Personal / Stay in Tune","Workout"];
const topics=["Meme / quote","Photo + meme or BTS","Photo animation","Hakuna Matata","Zen / family","OG Atlanta","Photo booth BTS","Angel Wings BTS","BEVCO / Infinity / Pronto BTS","Sole Exchange donors / location","Boardroom","Track & field offices BTS","Print shop: FĚNYX / STUSH","GOOD TIMES","Music BTS","Vegas move","Travel","Food tasting","New partners","Events"];
const uid=()=>Math.random().toString(36).slice(2,11);
const seed:Task[]=[...brands.map(brand=>({id:uid(),title:"Daily founder check-in",brand,category:"Research / Updates",target:1,done:0,status:"active" as const,owner:"CHAT",proof:"",time:""})),...background.map(brand=>({id:uid(),title:"Define next milestone",brand,category:"Research / Updates",target:1,done:0,status:"background" as const,owner:"CHAT",proof:"",time:""}))];
const shell:React.CSSProperties={minHeight:"100vh",background:"#0b0c10",color:"#f5f4f0",fontFamily:"Inter,Arial,sans-serif",padding:"28px clamp(14px,3vw,46px)"};
const panel:React.CSSProperties={border:"1px solid #34343a",background:"#17181d",borderRadius:16,padding:18};
const button:React.CSSProperties={border:"1px solid #57565b",background:"#24252c",color:"#fff",borderRadius:9,padding:"10px 13px",cursor:"pointer"};
const field:React.CSSProperties={...button,background:"#0f1015",width:"100%",boxSizing:"border-box"};
export default function FounderCommand(){
 const [tasks,setTasks]=useState<Task[]>(seed),[view,setView]=useState("Overview"),[brand,setBrand]=useState("ALL"),[date,setDate]=useState(""),[title,setTitle]=useState(""),[newBrand,setNewBrand]=useState("DORSEY"),[category,setCategory]=useState(categories[0]),[target,setTarget]=useState(1),[newBackground,setNewBackground]=useState(""),[filter,setFilter]=useState("all"),[hydrated,setHydrated]=useState(false);
 useEffect(()=>{setDate(new Date().toLocaleDateString("en-CA"));try{const saved=localStorage.getItem("khg-founder-command-v1");if(saved)setTasks(JSON.parse(saved))}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem("khg-founder-command-v1",JSON.stringify(tasks))},[tasks,hydrated]);
 const update=(id:string,change:Partial<Task>)=>setTasks(xs=>xs.map(x=>x.id===id?{...x,...change}:x));
 const add=(name:string,b:string,c:string,mode:"active"|"background"="active",n=1)=>{if(!name.trim())return;setTasks(xs=>[{id:uid(),title:name.trim(),brand:b,category:c,target:Math.max(1,n),done:0,status:mode,owner:"CHAT",proof:"",time:""},...xs]);setTitle("")};
 const shown=useMemo(()=>tasks.filter(t=>(brand==="ALL"||t.brand===brand)&&(filter==="all"||t.status===filter)),[tasks,brand,filter]);
 const active=tasks.filter(t=>t.status!=="background");const completed=active.filter(t=>t.done>=t.target).length;const percent=active.length?Math.round(completed/active.length*100):0;
 const section=(name:string,children:React.ReactNode)=><section style={panel}><h2 style={{fontSize:16,margin:"0 0 16px",letterSpacing:".06em"}}>{name}</h2>{children}</section>;
 const taskRow=(t:Task)=><div key={t.id} style={{display:"grid",gridTemplateColumns:"minmax(170px,2fr) minmax(90px,1fr) 75px auto",gap:12,alignItems:"center",padding:"12px 0",borderBottom:"1px solid #303138"}}>
  <div><div style={{fontWeight:700,fontSize:14}}>{t.title}</div><small style={{color:"#aba9ae"}}>{t.brand} · {t.category} · {t.owner}</small></div>
  <div style={{display:"flex",gap:6,alignItems:"center"}}><button style={button} aria-label="decrease" onClick={()=>update(t.id,{done:Math.max(0,t.done-1)})}>−</button><b>{t.done}/{t.target}</b><button style={button} aria-label="increase" onClick={()=>update(t.id,{done:Math.min(t.target,t.done+1)})}>+</button></div>
  <span style={{fontSize:12,color:t.done>=t.target?"#73daa4":t.status==="background"?"#e3c27c":"#f0a2a2"}}>{t.done>=t.target?"DONE":t.status==="background"?"BACKLOG":"OPEN"}</span>
  <button style={button} onClick={()=>update(t.id,{status:t.status==="background"?"active":"background"})}>{t.status==="background"?"Promote":"Defer"}</button>
 </div>;
 return <main style={shell}>
 <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:14,marginBottom:25}}><div><div style={{color:"#d6af79",fontSize:12,letterSpacing:3}}>DOLO COMMAND / FOUNDER OS</div><h1 style={{margin:"7px 0 4px",fontSize:"clamp(26px,3vw,42px)"}}>Daily Command Center</h1><div style={{color:"#a4a4ad"}}>Daily scorecard · schedule · background-to-execution pipeline</div></div><input type="date" value={date} onChange={e=>setDate(e.target.value)} style={{...field,width:180}}/></div>
 <nav style={{display:"flex",gap:7,flexWrap:"wrap",marginBottom:22}}>{["Overview","Scorecard","Schedule","Background","Dorsey Content"].map(v=><button key={v} style={{...button,background:view===v?"#c1a073":"#23242b",color:view===v?"#131313":"white"}} onClick={()=>setView(v)}>{v}</button>)}</nav>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:12,marginBottom:20}}>{[["Daily completion",percent+"%"],["Completed commitments",completed+" / "+active.length],["Background initiatives",tasks.filter(t=>t.status==="background").length],["Active focus brands",brands.length]].map(([label,value])=><div key={label} style={panel}><div style={{fontSize:12,color:"#a7a6ac"}}>{label}</div><div style={{fontSize:30,fontWeight:750,marginTop:8}}>{value}</div></div>)}</div>
 {(view==="Overview"||view==="Scorecard")&&<div style={{display:"grid",gap:16}}>
 {section("Create measurable commitment",<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:9}}><input style={field} placeholder="Task / deliverable" value={title} onChange={e=>setTitle(e.target.value)}/><select style={field} value={newBrand} onChange={e=>setNewBrand(e.target.value)}>{[...brands,...background].map(x=><option key={x}>{x}</option>)}</select><select style={field} value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select><input style={field} type="number" min="1" value={target} onChange={e=>setTarget(Number(e.target.value))}/><button style={{...button,background:"#a98657",color:"#141414"}} onClick={()=>add(title,newBrand,category,"active",target)}>+ Add commitment</button></div>)}
 {section("Daily execution scorecard",<><div style={{display:"flex",gap:9,marginBottom:12,flexWrap:"wrap"}}><select style={{...field,width:220}} value={brand} onChange={e=>setBrand(e.target.value)}><option>ALL</option>{[...brands,...background].map(x=><option key={x}>{x}</option>)}</select><select style={{...field,width:160}} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="background">Background</option></select></div>{shown.length?shown.map(taskRow):"No entries"}</>)}</div>}
 {(view==="Overview"||view==="Schedule")&&section("Daily schedule — editable time blocks",<><p style={{fontSize:13,color:"#aaa"}}>Suggested structure. Enter time slots on individual commitments; use this as a founder rhythm, not proof of work.</p><div style={{display:"grid",gap:8}}>{[["05:00–07:00","Research intelligence","DOT: source / enrich / identify"],["07:00–08:00","Personal / workout","Founder time"],["08:00–09:00","CEO planning","CHAT: priorities / GHL review"],["09:00–11:00","Creative + social QA","Brand-isolated approvals"],["11:00–13:00","Revenue decisions + closing","Founder / MUSE handoffs"],["13:00–15:00","Product and venue execution","Apps / partnerships / onboarding"],["15:00–17:00","Meetings, calls, follow-ups","Human approval required for outreach"],["17:00–18:00","Background initiative advancement","Milestones / conversion to active"],["18:00–19:00","Daily receipts + next-day plan","Verify evidence; no assumed completions"]].map(([time,block,owner])=><div key={time} style={{display:"grid",gridTemplateColumns:"110px 1fr",gap:12,padding:"11px 0",borderBottom:"1px solid #323339"}}><strong style={{color:"#d2b489",fontSize:12}}>{time}</strong><div><strong>{block}</strong><div style={{color:"#999aa3",fontSize:12,marginTop:4}}>{owner}</div></div></div>)}</div></>)}
 {(view==="Overview"||view==="Background")&&section("Background incubator → normal scorecard",<><p style={{color:"#aaa",fontSize:13}}>One-off opportunities stay separate from daily quotas. Promote only after a deliverable, owner, metric and deadline are defined.</p><div style={{display:"flex",gap:9,marginBottom:12,flexWrap:"wrap"}}><input style={{...field,maxWidth:350}} placeholder="Add background focus" value={newBackground} onChange={e=>setNewBackground(e.target.value)}/><button style={button} onClick={()=>{add("Define next milestone",newBackground,"Research / Updates","background");setNewBackground("")}}>+ Capture focus</button></div>{tasks.filter(x=>x.status==="background").map(taskRow)}</>)}
 {(view==="Overview"||view==="Dorsey Content")&&section("DORSEY / Editorial content rotation",<><p style={{color:"#aaa",fontSize:13}}>Topic bank only—not published or approved assets. Mix personal identity, enterprise BTS, culture, book, and lifestyle without presenting another brand's content as a Dorsey post.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8}}>{topics.map((x,i)=><button key={x} style={{...button,textAlign:"left"}} onClick={()=>add("Prepare DORSEY content: "+x,"DORSEY","Creative / Graphics")}>{String(i+1).padStart(2,"0")} · {x} <span style={{float:"right"}}>＋</span></button>)}</div></>)}
 <div style={{display:"flex",gap:12,justifyContent:"space-between",marginTop:24,flexWrap:"wrap",color:"#8f909a",fontSize:12}}><span>Workspace: browser-local prototype · not yet synchronized with Supabase or GHL · no sends are initiated</span><button style={button} onClick={()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),tasks},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="founder-scorecard.json";a.click();URL.revokeObjectURL(a.href)}}>Export JSON</button></div>
 </main>
}
